version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: nestapp
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - '3010:3010'
    env_file:
      - packages/backend/.env.prod
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - '3000:80'
    env_file:
      - packages/frontend/.env

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
