version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: nestapp
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - '3010:3010'
    env_file:
      - packages/backend/.env.prod
    depends_on:
      - db
    volumes:
      - ./packages/backend/dist:/app/dist

  frontend:
    container_name: frontend
    image: frontend
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3010
    ports:
      - '3000:3000'

  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
