version: '3.9'
services:
  frontend:
    container_name: frontend
    image: frontend
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    env_file:
      - .env
    command: yarn start
