version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: nestapp
    build: .
    ports:
      - '3010:3010'
    environment:
      - DB_TYPE=postgres
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
